Repository yu-devu/devu, pull requests merged in 2022-09, with the labels that each got.

#225 docs: Post 문서화 수정
  backend/BOOT-INF/classes/static/docs/api.html
  backend/src/docs/asciidoc/api.adoc
  backend/src/test/java/com/devu/backend/controller/post/PostControllerTest.java
Labels: documentation

#229 feat: 취업 정보 검색 추가
  frontend/src/components/Jobs/Jobs.js
Labels: Front End

#232 fix: 대댓글 수정
  backend/src/main/java/com/devu/backend/repository/comment/CommentRepository.java
  backend/src/main/java/com/devu/backend/service/CommentService.java
  backend/src/main/java/com/devu/backend/service/PostService.java
  backend/src/test/java/com/devu/backend/api/comment/CommentApiControllerTest.java
Labels: fix
